FROM ruby:2.6.3
RUN apt-get update -qq && apt-get install -y build-essential nodejs npm default-mysql-client && npm i -g yarn
RUN mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install
ADD package.json /app
ADD yarn.lock /app
RUN yarn install
ADD . /app
